### ISSUE TITLE
License file doesn't install automatically in EAP 7

### ISSUE THREAD

**Issue by pearj** [Dynatrace/Dynatrace-Docker#12]
In the EAP 7 branch setting `DT_SERVER_LICENSE_KEY_FILE_URL=<something>` doesn't actually do anything.  I had to apply the license via the thick client instead.

I don't see any references to any script actually calling `https://github.com/Dynatrace/Dynatrace-Docker/blob/EAP_7.0.0.2346/Dynatrace-Server/build/scripts/pull-license-key-file.sh`

I even tried running that script at boot, and it copied the license in place, but it didn't do anything.

**Comment by BlazejT** [comment]
Hi @pearj 

Thanks for the feedback. It is fixed in [7fafab3](url=https://github.com/Dynatrace/Dynatrace-Docker/commit/7fafab3a7c763893004401f0e12790d70ba39cdf). Let us know if it works for you.

Thanks,
BT
