### ISSUE TITLE
Optional license pull script stores license under wrong name 

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [Dynatrace/Dynatrace-Docker#14]
The pull-license.sh script copies an arbitrary licnese file from an URL to the server directory, however this script doesn't work properly if the license is not called "dtlicense.key|lic"

The target file always has to be dtlicense.lic (7.0+) or dtlicense.key (<7.0).

so the script should always create these files.

**Comment by reinhard-brandstaedter** [comment]
my patched and simplified script:

    #!/bin/bash
    if [ ${DT_SERVER_LICENSE_KEY_FILE_URL} ]; then
      DT_SERVER_LICENSE_KEY_FILE="${DT_HOME}/server/conf/dtlicense.lic"
    
      curl -L -o ${DT_SERVER_LICENSE_KEY_FILE} ${DT_SERVER_LICENSE_KEY_FILE_URL}
      chmod 0600 ${DT_SERVER_LICENSE_KEY_FILE}
    fi

**Comment by MarcinZejer** [comment]
Hi Reinhard,
Thanks a lot for your help.
I commited fix as you suggested 38b0aca89a0abae430e40b893c654757dbe2635e
