### ISSUE TITLE
Document resource requirements

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-Docker#2]
I just ran docker compose-up on my machine, but the Docker Toolbox comes with 1 vcpu and 1024 mb ram default. This did not make Dynatrace happy.
Please advise to these recommendations in the documentation.

**Comment by metmajer** [comment]
Great catch @tutnes and thanks for the reminder. A section on "Resource Requirements" has just been added to [README.md](https://github.com/Dynatrace/Dynatrace-Docker/blob/master/README.md).
