### ISSUE TITLE
Create a version for 6.5?

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-Docker#5]
Hi, would it be possible to create a version for 6.5 EAP?

**Comment by metmajer** [comment]
It is not planned to create publicize Docker images for non-public Dynatrace builds. Thanks for your understanding.

**Comment by metmajer** [comment]
AppMon 6.5 images are currently under preparation. Stay tuned!

**Comment by metmajer** [comment]
AppMon 6.5 in Docker has just been made available. Enjoy! @tutnes @dtPaTh
