### ISSUE TITLE
Getting "not found" after building for the two .sh scripts

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-Docker#6]
Hi I am running Docker Beta for Windows.

I am able to build the Dynatrace Server without any errors except the security warning:

> SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

But when I try to run the image afterwards I get this:

`/bin/sh: 1: /pull-license-key-file.sh: not found
/bin/sh: 1: /run-process.sh: not found`

**Comment by metmajer** [comment]
Obviously, the files in https://github.com/Dynatrace/Dynatrace-Docker/tree/master/Dynatrace-Server/build/scripts are not being picked up when you generate the image under the Docker Beta for Windows. Have you been successful in the meantime?

**Comment by metmajer** [comment]
@tutnes. Closed due to inactivity. Feel free to reopen if the problem persists.
