### ISSUE TITLE
Create an image for 7.0

### ISSUE THREAD

**Issue by kaushald** [Dynatrace/Dynatrace-Docker#9]
Signing up for Dynatrace AppMon trial at date of posting this generates a license for v7.0
Could images be generated for v7 so that there is a docker alternative to the win/linux/mac install options?

**Comment by BlazejT** [comment]
Hi @kaushald, please check [EAP_7.0.0.2346](url=https://github.com/Dynatrace/Dynatrace-Docker/tree/EAP_7.0.0.2346) branch.
